
- hosts: all

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_nist-800-171-cui
    oscap_policy: ssg-rhel7-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/nist-arf.xml \
        --report /tmp/nist-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:
    - name: download report
      fetch:
        src: /tmp/nist-report.html
        dest: ../oscap-reports/{{ inventory_hostname }}.html
        flat: yes